### ISSUE TITLE
Code to call WIG like a function

### ISSUE THREAD

**Issue by portantier** [jekyc/wig#10]
Hi! 

First of all, WIG is awesome!!!

Second, I don't know how to post code, so, I'm opening an issue, but that isn't really an issue.

I've wrote a code to call WIG like a function that returns the results array like the obtained with de "get_results()" function.

The code it's below:

import sys

import argparse

from wig import Wig

def wigcall(url):

    parser = argparse.ArgumentParser()

    args = parser.parse_args()

    args.input_file = None
    args.url = url
    args.user_agent = 'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2049.0 Safari/537.36'
    args.proxy = None
    args.verbosity = 0
    args.run_all = False
    args.match_all = False
    args.stop_after = 1
    args.no_cache_load = False
    args.no_cache_save = False
    args.output_file = None

    w  = Wig(args)

    w.options['interactive'] = False

    w.reset()

    oldprint = print

    oldstdout = sys.stdout

    sys.stdout = None

    w.scan_site()

    sys.stdout = oldstdout

    return w.data['results'].get_results()

And you can call it with a code like this:

from wigcall import wigcall

results = wigcall('www.google.com')

print(results)

PD: I've think that the code to supress stdout can be deleted or improved, I've just appended that to simplify the utilization of the code.

Regards! :)

**Comment by jekyc** [comment]
Hi portantier,

Thank you for the nice words and feature suggestion. 

I think it would be a great feature to add to wig, and I'll look into how it could be implemented. I'll leave this issue open until the feature is implemented and release.

**Comment by jekyc** [comment]
Hi portantier,

I've updated wig to include native support for calling it as a function:
```
>>>> from wig import wig
>>>> w = wig(url='example.com')
>>>> w.run()
>>>> results = w.get_results()
```

The 'url' parameter is required, but all of wigs other options are optional.

Thanks for the feedback and comments - keep'em coming!
