### ISSUE TITLE
ImportError: No module named queue

### ISSUE THREAD

**Issue by JohnnyAMD** [jekyc/wig#13]
Hi, 

Trying to use wig with python 2.7 I'm getting this error:

"nsck (most recent call last):
  File "wig.py", line 29, in <module>
    import time, queue, sys, argparse
ImportError: No module named queue
"
Which queue module actually has to be installed? I'm asking that because doing a "pip search queue" I'm getting way to much related results. 

Thanks!

**Comment by jekyc** [comment]
Hi Johnny,

Currently wig requires Python 3, and it will not run under Python 2.x, which is why you're seeing the ImportError.

Please see issue https://github.com/jekyc/wig/issues/12 which is also related to Python 2.x support.
