### ISSUE TITLE
Can't get url list file to work

### ISSUE THREAD

**Issue by trond7** [jekyc/wig#16]
When i try to get wig to parse i file with links it fails.
**Command:**
```sh
python3 wig.py -l sites.txt
```

**I get this error mesage**
```sh
Traceback (most recent call last):
  File "wig.py", line 383, in <module>
    wig = Wig(args)
  File "wig.py", line 62, in __init__
    'url': args.url.lower(),
AttributeError: 'NoneType' object has no attribute 'lower'
```

Using wig for singular url work fine
```sh
python3 wig.py domain.com
```

I have tried url's with and without http/www

**My environment**
Ubuntu 12.04
editor NANO
Both python 2.7.3 and python3.2.3 installed
sites.txt --> file permission 777
wig git pull --> up to date
I have used url from list before

**Comment by jekyc** [comment]
Hi trond7,

Thanks for the bug report! 
I just pushed a fix for the issue - could you please test it and report back if it works for you ?

**Comment by trond7** [comment]
Hi jekyc, 

Tanks for the lightning fast respons.
It works fine now.

Keep up the good work.
Wig is a really nice tool

**Comment by jekyc** [comment]
Hi trond7,

Thanks for the kind words, and I'm glad that the fix worked. 

I'll close the issue.

- jekyc
