### ISSUE TITLE
Why Wig doesn't work?

### ISSUE THREAD

**Issue by bywwq** [jekyc/wig#17]
The Wig can work 2 months ago when I knew that. But today I ran the same code, it failed, and I try to download the latest version just now and run again, either can run, the screenshot is below, thanks for answers!
![image](https://cloud.githubusercontent.com/assets/4220129/10390315/6705e6c0-6eaa-11e5-90f9-b230662ea9d4.png)
python version is 3.5.0
The wig.py I jusr download is under \wig-master

Thank you so much!

**Comment by bywwq** [comment]
I change the python's version from 3.5 to 3.4, then it works!

**Comment by jekyc** [comment]
Hi bywwq,

Thanks for the bug report. 
I haven't tested wig on 3.5 yet, but I'll look into the issue as soon as possible. I'm glad you got it working under 3.4.

**Comment by jamesacampbell** [comment]
If anyone is getting a 'strict' error during runtime, you need to remove the strict part of the discovery.py script and then it works fine. I am going to try to issue a pull request with my fixes in place.

**Comment by bywwq** [comment]
Thank you for your attention. Looking for latest version from you.

**Comment by jekyc** [comment]
Hi bywwq,

Could you please test if the latest commit fixes the issue you were are seeing?
