### ISSUE TITLE
Change the DiscoverIP result to a IP set.

### ISSUE THREAD

**Issue by cwll2009** [jekyc/wig#19]
Sometimes a domain have more than one ip address. In the file "results.py", class "Results" ,function "__init__" ,change the "site_info.ip" to a set. In the file "discovery.py",class "DiscoverIP" ,function "run",change line "ip = socket.gethostbyname(hostname)" to "ip = socket.gethostbyname_ex(hostname)[2]".

**Comment by jekyc** [comment]
Hi cwll2009,

Thanks for the suggestion. 

I've implemented it in the latest series of commits. Could you please pull the latest version, and check it is working for you?

**Comment by cwll2009** [comment]
Hi jekyc,
I tried. It works.
