### ISSUE TITLE
User Defined Cache directory

### ISSUE THREAD

**Issue by archey** [jekyc/wig#24]
Would it be possible to add an option to allow the user to define the location of the cache directory?

**Comment by jekyc** [comment]
Hi archey,

Sorry about the late reply. I've just committed an implementation of your suggestion - could you please test it and see if it works for you?

**Comment by archey** [comment]
@jekyc  looks good let me pull it down and test it and Il let you know

**Comment by archey** [comment]
@jekyc works great thanks for the fix
