### ISSUE TITLE
Support to Cyrillic sites

### ISSUE THREAD

**Issue by grimnir** [jekyc/wig#5]
Please if possible make support for sites with russian language. Now any site return error
Traceback (most recent call last):
  File "wig.py", line 229, in <module>
    wig.run()
  File "wig.py", line 171, in run
    print(outputter.get_results())
  File "C:\python3\App\lib\encodings\cp866.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2014' in position 37: character maps to <undefined>

**Comment by jekyc** [comment]
Hi grimnir,

Thanks for the bug report. I've made a quick fix for the issue. If the title contains non-ascii chars, it does not get printed  - it isn't pretty and hopefully I'll find a better fix at some point, however, it should make it possible to print detected versions.

**Comment by grimnir** [comment]
Hi jekyc ,
Now is working as well  ,thank you for fast support!
