### ISSUE TITLE
Make Wig read URL's from a list of URL and then write the result to file.

### ISSUE THREAD

**Issue by trond7** [jekyc/wig#6]
I have been using your CMS/app sniffer quite frequently and are happy with its accuracy.

I have a feature request that would make this tool much better for my use cases.

**Feature:**
Have the option to make Wig read URL's from a list of URL and then write the result to file.

**Solution suggestion**
wig could read a simple .txt file with one URL on each line.
Wig could then write the result to one file for each url (sub.domainname.txt) or aggregated the output to one common result file.

I would prefer if the result was written in a structured manner like a .csv file or similar.

**Example use case**
- What is the complete list of tecknology used for my own organisations sites.
- What kind of CMS is my clients using?
- What is the most popular CMS used by this group of organisations?
- What is the most common version of drupal used by this drupal sites?
- What is the most popular operating system among this sites?

Thanks for sharing this tool and keep up the good work.

**Comment by jekyc** [comment]
Hi trond7,

Thanks for the feedback - it's nice to know that others are happily using wig as well :)

I've added preliminary support for loading urls from a file and saving the results to a single file. Currently the only format supported for output is JSON. I plan on adding XML later on. These features are available from 0.5.2.

Note: there might some issues with result bleeding if you use the caching functionality. I'd suggest you wipe the /cache dir before trying out the new features.
