### ISSUE TITLE
Handle unresponsive or unknown host gracefully

### ISSUE THREAD

**Issue by olamotte** [jekyc/wig#8]
in wig.py on  line 87: except UnknownHostName as e:

Suggestion: commenting and returning keeps the loop going when using a list with -l
                  90:     - sys.exit(1) 
                  90:     + return

**Comment by jekyc** [comment]
Hi olamotte,

Thanks for the bug report and fix suggestion. I've just pushed a fix for the issue. Could you please test if this works for you?
